import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import globalsAll from 'globals';

const CALLBACKS = 'map|filter|some|every|find|findIndex|findLast|findLastIndex';
const BRANCH = ':matches(LogicalExpression, ConditionalExpression)';

export default defineConfig([
	{ name: 'runner/files', files: ['src/**/*.mjs'] },
	globalIgnores(['node_modules/**', 'work/**', 'eslint.config.mjs']),
	js.configs.recommended,
	{
		name: 'runner/rules',
		plugins: { '@stylistic': stylistic },
		languageOptions: { globals: globalsAll.node },
		rules: {
			'@stylistic/indent': ['error', 'tab'],
			'@stylistic/no-tabs': ['error', { allowIndentationTabs: true }],
			'@stylistic/max-len': ['error', { code: 180, tabWidth: 2, ignoreUrls: true }],
			'@stylistic/semi': ['error', 'always'],
			'@stylistic/no-extra-semi': 'error',
			'@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
			'@stylistic/space-before-blocks': ['error', 'always'],
			'@stylistic/no-mixed-operators': 'error',
			'@stylistic/no-multi-spaces': ['error', { exceptions: { Property: true, AssignmentExpression: true } }],
			'@stylistic/key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
			'@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
			'@stylistic/no-trailing-spaces': 'error',
			'@stylistic/eol-last': ['error', 'always'],
			'@stylistic/linebreak-style': ['error', 'unix'],
			'@stylistic/nonblock-statement-body-position': ['error', 'beside'],
			'@stylistic/padding-line-between-statements': ['error',
				{ blankLine: 'never', prev: 'import', next: 'import' },
				{ blankLine: 'always', prev: '*', next: 'return' },
				{ blankLine: 'always', prev: 'block-like', next: '*' },
				{ blankLine: 'always', prev: ['multiline-const', 'multiline-let'], next: '*' },
				{ blankLine: 'any', prev: ['multiline-const', 'multiline-let'], next: ['const', 'let'] },
				{ blankLine: 'always', prev: 'expression', next: ['const', 'let'] },
			],
			'curly': ['error', 'multi-line'],
			'camelcase': ['error', { properties: 'never' }],
			'eqeqeq': ['error', 'always', { null: 'ignore' }],
			'no-return-assign': ['error', 'always'],
			'no-unused-expressions': 'error',
			'no-empty': ['error', { allowEmptyCatch: true }],
			'no-var': 'error',
			'prefer-const': 'error',
			'block-scoped-var': 'error',
			'no-shadow': 'error',
			'one-var': ['error', 'never'],
			'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
			'no-param-reassign': ['error', { props: false }],
			'no-nested-ternary': 'error',
			'max-params': ['error', 4],
			'max-depth': ['error', 3],
			'no-restricted-syntax': ['error',
				{ selector: 'ImportDeclaration[source.value=/^\\./]:not([source.value=/\\.(js|mjs)$/])', message: 'A relative import states the full filename, including its extension.' },
				{ selector: 'VariableDeclarator[id.name!=/_REGEX$/] > Literal[regex]', message: 'Name a regex const <THING>_REGEX.' },
				{ selector: `ArrowFunctionExpression > ${BRANCH}.body ${BRANCH}`, message: 'An expression-bodied arrow has at most one branch (||, &&, ??, ?:). Write a named function.' },
				{ selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name=/^(reduce|reduceRight|forEach|flatMap)$/]', message: 'No reduce, forEach or flatMap. Write a for loop.' },
				{ selector: `CallExpression[callee.type="MemberExpression"][callee.property.name=/^(${CALLBACKS})$/]:not([arguments.0.type="ArrowFunctionExpression"][arguments.0.body.type!="BlockStatement"])`, message: 'A callback method takes one expression-bodied arrow. Anything else is a for loop.' },
				{ selector: `CallExpression[callee.property.name=/^(${CALLBACKS})$/][callee.object.type="CallExpression"][callee.object.callee.property.name=/^(${CALLBACKS})$/]`, message: 'No callback chains. One call, or a for loop.' },
				{ selector: ':matches(VariableDeclarator > LogicalExpression.init, AssignmentExpression > LogicalExpression.right)[operator="||"]', message: 'No || defaulting. Declare the default, then an if that overrides it.' },
				{ selector: 'CallExpression > MemberExpression.callee[property.name="then"]', message: 'No .then. Await the call.' },
				{ selector: 'MemberExpression[object.name="Promise"][property.name=/^(all|allSettled|any|race)$/]', message: 'No Promise.all. Await each call in spec order.' },
				{ selector: 'ClassDeclaration, ClassExpression', message: 'No classes. Plain objects and functions.' },
				{ selector: 'NewExpression[callee.name="RegExp"], CallExpression[callee.name="RegExp"]', message: 'No RegExp built at run time. Write the literal, or use string methods.' },
				{ selector: 'Literal[regex.pattern=/^[^\\\\\\[\\]()^$.*+?{}|]*$/]', message: 'This regex has no metacharacters; it is a string. Use includes, indexOf or replaceAll.' },
			],
		},
	},
]);
